### ISSUE TITLE
New IAM Enabled check breaks code where ALKS use is optional

### ISSUE THREAD

**Issue by duckpuppy** [Cox-Automotive/terraform-provider-alks#123]
We have a module that CAN use alks to manage IAM resources if needed, but it's not required (and indeed not possible) in some environments. Since there's no way to declare a provider as optional in the `required_providers` stanza in the module itself, we always declare the provider in the code using the module so the module has the reference, but the usage of `alks_iamrole` resources in the module will be conditionally removed when not needed.

Now that the provider checks for the credentials being used to be IAM Enabled, we can no longer do this. Even plans fail with

```
11:59:20 Error: Looks like you are not using ALKS IAM credentials. This will result in errors when creating roles. 
11:59:20  Note: If using ALKS CLI to get credentials, be sure to use the '-i' flag. 
11:59:20  Please see https://coxautoinc.sharepoint.com/sites/service-internal-tools-team/SitePages/ALKS-Terraform-Provider---Troubleshooting.aspx for more information.
11:59:20 
11:59:20   on main.tf line 23, in provider "alks":
11:59:20   23: provider "alks" {
11:59:20 
11:59:20 
```

Is there any way to not do this check until the provider is actually trying to create an `alks_iamrole` resource rather than provider initialization time?

**Comment by amagana3** [comment]
@duckpuppy sorry about this! This is a new change that was brought in and it seems to have a bug. We're in the process of fixing this. Can you revert back to using ALKS TFP version `v1.5.12` ? This does not include the latest change and will work as it did previously.
