### ISSUE TITLE
Export ip_name attribute

### ISSUE THREAD

**Issue by brasey** [Cox-Automotive/terraform-provider-alks#14]
When configuring an `aws_instance` resource, the `iam_instance_profile` attribute requires the instance profile *name*, not its *ARN*. Can you also export `ip_name` along with `ip_arn`?

**Comment by kennyg** [comment]
the instance profile name is available like so:
`iam_instance_profile  = "${alks_iamrole.your_role.name}"`

**Comment by brasey** [comment]
So you're saying instance profile name = IAM role name?

I feel sure I tested that, but maybe not...

**Comment by brianantonelli** [comment]
The instance profile name is the name of the role specified in `alks_iamrole` like @kennyg referenced above.
