### ISSUE TITLE
Seperate `iamtrustrole` from `iamrole`

### ISSUE THREAD

**Issue by sbrinkerhoff** [Cox-Automotive/terraform-provider-alks#147]
**Summary**

Currently the `alks_iamrole` and `alks_iamtrustrole` are contained together within `resource_alks_iamrole.go` and should be separated into separate files, such as `resource_alks_iamtrustrole.go`.

**Comment by amagana3** [comment]
Fixed here: https://github.com/Cox-Automotive/terraform-provider-alks/pull/148. Closing!
