### ISSUE TITLE
versioning

### ISSUE THREAD

**Issue by jgerry** [Cox-Automotive/terraform-provider-alks#21]
Can I make a suggestion that we properly version the ALKS provider as outlined here? https://www.hashicorp.com/blog/hashicorp-terraform-provider-versioning

It looks to be pretty simple, just following a naming scheme for the release binaries. `terraform-provider-NAME_vX.Y.Z`

**Comment by DTTerastar** [comment]
Agreed!! And Release either the binary or an archive.  Not either depending on platform...

**Comment by brianantonelli** [comment]
Completed
