### ISSUE TITLE
Add support for AWS tagging

### ISSUE THREAD

**Issue by jcarlson** [Cox-Automotive/terraform-provider-alks#28]
Would be great if this provider would support pass-through for `tags`, like the native `aws_iam_role` resource does.

```tf
resource "alks_iamrole" "my_role" {
  name = "my-role"
  type = "AWS CodeBuild"
  tags = {
    app = "my app"
    env = "my env"
  }
}
```

**Comment by aaron-seitz** [comment]
The Internal Tools team has discussed this issue - we agree there's definitely a benefit and need here, especially moving forward as we consider cost optimization more.

We have a story made which we will look further into during our next refinement session.

**Comment by vincentclee** [comment]
Any updates on this story to support AWS tagging on ALKS IAM roles?

**Comment by jasonrberk** [comment]
it would be nice to call out the limitation here: https://coxautoinc.sharepoint.com/sites/service-internal-tools-team/SitePages/How-to-Create-Roles-in-AWS-using-ALKS.aspx#create-role-2

**Comment by ekozlowski** [comment]
Good suggestion @jasonrberk.  I've called that out on the support page.  I've also called this issue to the teams attention, and worked on implementing this myself.  The issue (as it stands) is that it requires work to ALKS Core to proceed.  The ALKS Core API doesn't support tags (yet).  I'm seeing what I can do on that front as well.

Thanks for your patience!  🙂

**Comment by ekozlowski** [comment]
There is also some IAM work we've uncovered that we'll need to do to support this.  Thanks for digging with me @webbbarker  :)

**Comment by aaron-seitz** [comment]
This is tied to this request in from Jason (his request is for the ALKS side of tagging, which is a pre-req for this work). 

However, that work is also blocked by work outside our team - as such, I would not expect any resolution on this issue this year.

**Comment by andrewwatson** [comment]
Just wanted to check in and see if there was anything I could do to help unblock this :)

**Comment by webbbarker** [comment]
Hey @andrewwatson, unfortunately not right now (is that correct @aaron-seitz @ekozlowski?).  We're blocked on the ALKS side of things by work on the CAI account SCPs and user deny policies.  Until the Cloud Core team finalizes that the changes to enable IAM resource tagging we cannot roll out support.  For what it's worth, the ALKS team is also eagerly waiting for this feature for use internally.  😄

**Comment by vincentclee** [comment]
bump

**Comment by cdowney** [comment]
Is this resolved by https://github.com/Cox-Automotive/terraform-provider-alks/pull/165 ?

**Comment by codykoelemay** [comment]
Hey @cdowney, yes  #165 adds support for tagging in version 2.2.0 of the TFP. So I'll go ahead and close this issue.
