### ISSUE TITLE
Check if STS is Admin

### ISSUE THREAD

**Issue by brianantonelli** [Cox-Automotive/terraform-provider-alks#44]
Users who don't open an admin iam session (`-i`) are encountering errors:
```
* alks_iamrole.optimizely_lambda_service_role: Error creating role: Could not resolve 409336414461/ALKScdclose to a valid ALKS account
```

Let's add functionality to check if the session is an iam session like we do with t7t. Here's the code we use to validate admin, we'll need to do IAMAdmin as well..

```
  local role=`aws sts get-caller-identity --query '[Arn]' --region "$REGION" --output text`
  if [[ $role != *"assumed-role/Admin/"* ]]; then
    return 0
  else
    return 1
  fi
```

**Comment by amagana3** [comment]
This has been implemented in this PR: https://github.com/Cox-Automotive/terraform-provider-alks/pull/72
