### ISSUE TITLE
Unable to apply service role to elastic beanstalk

### ISSUE THREAD

**Issue by snoworc** [Cox-Automotive/terraform-provider-alks#45]
in eb, you can specify both an ec2-role and a service role.

Using terraform with alks provider, we are seeing the ec2_role is applied, but ServiceRole is not.

This happens on this a specific account. However when Kevin T.  tried this on another account (one of his), it did work there. Just not here. So, this is one is a little odd. 

The only other difference i noticed by looking at the state file, is ec2-role computes this:                             "role_added_to_ip": "true",

where as the service-role computes this:
"role_added_to_ip": "false",

module "beanstalk" {
  source = "../../components/beanstalk"
 ...
  beanstalk_service_role = "${alks_iamrole.beanstalk_service.arn}"
  beanstalk_ec2_role = "${alks_iamrole.beanstalk_ec2.ip_arn}"
}

resource "alks_iamrole" "beanstalk_service" {
  name                     = "${aws_elastic_beanstalk_application.example.name}-beanstalk-service-role"
  type                     = "AWS Elastic Beanstalk"
  include_default_policies = true
}

variable "beanstalk_service_role" {
  default = "aws-elasticbeanstalk-service-role"
}

setting {
    namespace = "aws:elasticbeanstalk:environment"
    name = "ServiceRole"
    value = "${var.beanstalk_service_role}"
  }

**Comment by david-woodruff** [comment]
This is an issue with the Elastic Beanstalk Service assuming that your role is built in the `/` path. You can work around this by formatting the `/acct-managed/` path as the role name you pass for the elastic beanstalk service role.
```
${format("%s/%s", "acct-managed", alks_iamrole.aws-elasticbeanstalk-service-role.name)}
```

The other behavior is probably due to a pre-seeded EB Service role in the `/` path on your account, not an ALKS Built role in the `/acct-managed/` path

**Comment by aaron-seitz** [comment]
Is this still an issue, or did David's need resolve? I'm closing this - future support questions can be sent to the [#alks-client-support](https://coxauto.slack.com/archives/C4C5MKVQ9) Slack channel.
