### ISSUE TITLE
ALKS Username Password from Keychain does not work.

### ISSUE THREAD

**Issue by Smuggla** [Cox-Automotive/terraform-provider-alks#5]
I was about to fork this project and have it read from alks.db like the cli but noticed that there is some functionality already built, it this not in the release version?

https://github.com/Cox-Automotive/terraform-provider-alks/blob/master/password_darwin.go

**Comment by devinsba** [comment]
No it's not in the current release. I think it was a simple oversight that it didn't get released. There should probably be a README update to go with that change though now that I think about it. I may PR that.

cc @brianantonelli

**Comment by brianantonelli** [comment]
This was accidentally published to `master` but still needs some work. The library being leveraged doesn't work properly.

**Comment by brianantonelli** [comment]
Resolved in @0.9.11 release.
