### ISSUE TITLE
Pull Credentials from Container for ECS and CodeBuild environments

### ISSUE THREAD

**Issue by david-woodruff** [Cox-Automotive/terraform-provider-alks#50]
To better match the default AWS TF Provider's capability the credentials from containers should be pulled in automagically like the default AWS TF Provider.

I spoke to @webbbarker about this already and he helped compile some of this information.

This is the implementation of this on the default AWS TF Provider
https://github.com/hashicorp/aws-sdk-go-base/blob/master/awsauth.go#L197

Here are some additional links
This is the 5th in line to be used as a credential source
https://docs.aws.amazon.com/cli/latest/userguide/cli-chap-configure.html#config-settings-and-precedence

Additional AWS Documentation
https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-iam-roles.html

Terraform doc on the subject
https://www.terraform.io/docs/providers/aws/index.html#ecs-and-codebuild-task-roles

**Comment by aaron-seitz** [comment]
We looked at this during Refinement - we've created a story in the backlog, will look at it in an upcoming sprint.

**Comment by webbbarker** [comment]
Closed by #53
