### ISSUE TITLE
Add support for "version" in provider config

### ISSUE THREAD

**Issue by jcarlson** [Cox-Automotive/terraform-provider-alks#51]
Like the AWS provider, it would be nice to support a "version" attribute on the provider, so that developers get a reasonable error message when their installed version of the provider is not new enough to support new features.

For example, I have provider version 1.0.0 installed and tried to create a new trust role with `enable_alks_access`. The following error message was cryptic and misleading:

```
Error: alks_iamtrustrole.my_trust_role: : invalid or unknown key: enable_alks_access
```

(The solution was to upgrade my ALKS provider, but there is no way to specify the minimum version required in your Terraform configuration).

**Comment by webbbarker** [comment]
@jcarlson you can accomplish this by adding a version constraint to the provider declaration.  For example:
```terraform
provider "alks" {
  url     = "https://alks.coxautoinc.com/rest"
  version = "~> 1.2.0"
}
```

That version constraint will be checked against the name of the plugin in your `~/.terraform.d/plugins` directory, specifically looking at the version listed in the plugin file name, like `terraform-provider-alks_v1.2.2`.  Documentation [here](https://www.terraform.io/docs/configuration/providers.html#plugin-names-and-versions).

I've also gone ahead and updated the examples listed in the README with version constraints for the most current release.

**Comment by aaron-seitz** [comment]
This should have resolved the need, no follow has occurred. Closing.
