### ISSUE TITLE
Include client name and version in User-Agent header

### ISSUE THREAD

**Issue by ntangy** [Cox-Automotive/terraform-provider-alks#52]
We'd like each ALKS client application to return information about its name and version to the ALKS API when executing requests. This information will be used to gather user information and gather insight to aid in troubleshooting. To standardize across technologies, we'd like this client to use the standard User-Agent header to specify its name and version (plus any additional useful information specific to the tool). See the RFC for more details on this
https://tools.ietf.org/html/rfc2616?spm=5176.doc32013.2.3.Aimyd7#section-3.8

**Comment by webbbarker** [comment]
Closed by #55
