### ISSUE TITLE
Fix Public TF Registry Setup

### ISSUE THREAD

**Issue by arseitz** [Cox-Automotive/terraform-provider-alks#62]
TIL: The ALKS Terraform provider is in the public TF Registry, but you can't use it there because it's setup incorrectly (and hence why you have to do the 'ole cURL install procedure)

**Comment by arseitz** [comment]
Closing, as we determined that this wasn't going to be possible due to expectations in TF Registry that don't match our development.

**Comment by dkolb** [comment]
Can we have an explanation on this decision?  This single decision has spawned more custom docker images just for deploying pure terraform code in our BU.  We could be easily using Hashicorp provided images to do our deployments if it were not for this single provider refusing to be on the TF registry.

**Comment by jantman** [comment]
Per https://www.terraform.io/docs/registry/providers/docs.html#publishing, publishing providers to the Terraform Registry is currently in a public beta, and not yet open to the full community.

Granted, we do have some connections with Hashicorp. I'm relatively confident we could get into the public beta if we want to.

**Comment by bondezbond** [comment]
+1
