### ISSUE TITLE
[Feature Request] Switch between ALKS Accounts

### ISSUE THREAD

**Issue by webbbarker** [Cox-Automotive/terraform-provider-alks#71]
As a user of the TFP, it'd be nice if I could switch between other ALKS accounts I have access to directly in the provider definition.  Specifically, if I am authenticated as a user with (STS credentials to an ALKS managed role) I would like to be able to switch to another account and role that I also have access to.  This would enable me to more eloquently manage cross account resources manually, for example ACM and Route53.

This can be managed today via manually embedding multiple keys or using a credentials file, but it would be helpful if the TFP could handle this directly.

Perhaps something that looks a bit like:
```terraform
provider "alks" {
   url     = "https://alks.foo.com/rest"
   version = "~> 1.3.0"
   switch_accounts {
      account_number = "1234567890"
      role = "Admin"
   }
}
```

**Comment by jcarlson** [comment]
Linking to some useful context: https://coxauto.slack.com/archives/C4C5MKVQ9/p1588178119146800

In particular:
> So perhaps a properly configured ALKS provider would allow me to transitively configure one (or more) AWS providers 🤔. As in, the ALKS provider could provide a `data` resource that returns credentials for an account?

**Comment by amagana3** [comment]
This feature has been released: https://github.com/Cox-Automotive/terraform-provider-alks/releases/tag/1.5.2
